import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { useState, useEffect } from 'react';
import Link from 'next/link';


const defaultEndpoint = 'https://rickandmortyapi.com/api/character/';
export async function getServerSideProps () {
  const res = await fetch(defaultEndpoint);
  const data = await res.json();
  return {
    props: {
        data,
    }
  }
}


export default function Home({data}) {
  const {info, results: defaultResult =[]} = data;
  const [results, updateResult] = useState(defaultResult);
  const [page, updatePage] = useState({
    ...info,
    current: defaultEndpoint
  });
  const {current} = page;

  useEffect(() => {
    if(current === defaultEndpoint) return;
      async function request(){
        const res = await fetch(current);
        const nextData = await res.json();
        updatePage({
          current,
          ...nextData.info
        })
      if(!nextData.info?.prev){
        updateResult(nextData.results);
        return;
      }
      updateResult(prev => {
        return[
          ...prev,
          ...nextData.results
        ]
      })
    };
      request();
  }, [current]);

  function handleLoadMore(){
    updatePage(prev => {
      return {
        ...prev,
        current: page?.next
      }
    })
  }

  function handleSearch(e){
    e.preventDefault();
    const {currentTarget = {}} = e;
    const fields = Array.from(currentTarget?.elements);
    const fieldQuery = fields.find(field => field.name === 'query');

    const value = fieldQuery.value || '';
    const endpoint = `https://rickandmortyapi.com/api/character/?name=${value}`;

    updatePage({
      current: endpoint
    });
  }
  

  return (
    <div className={styles.container}>
      <Head>
        <title>Rick Morty API</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Wubba Lubba dub dub
        </h1>

        <p className={styles.description}>
           Rick and Morty
        </p>
          <form className={styles.search} onSubmit={handleSearch}>
            <input type='search' name='query'/>
            <button>Search</button>
        </form>
        <ul className={styles.grid}>
          {results.map((result)=> {
              const {id, name, image} = result;
          
                return(
            <li key={id} className={styles.card}>
              <Link href={"/character/[id]"} as={`/character/${id}`}>
              <a>
                <img src={image} alt={`${name} Thumb`}/>
                <h2>{name}</h2>
              </a>
              </Link>
            </li>
          )
          })}
        </ul>
          <p>
            <button onClick={handleLoadMore} className={styles.button}>Load More</button>
          </p>
      </main>
      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
